name: Release (development)
on:
  push:
    paths:
      - 'prometheus/**'
      - '.github/workflows/prometheus.yaml'

jobs:
  build:
    name: Build And Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code into the Go module directory
      uses: actions/checkout@v1

    - name: Build binaries
      run: |
        make prometheus archive=${{ github.workspace }}/build/prometheus

    - name: Publish flist no base
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: publish
        user: tf-autobuilder
        root: build/prometheus
        name: prometheus-bins.flist

    - name: Publish flist
      uses: threefoldtech/publish-flist@master
      with:
        action: merge
        user: azmy
        name: prometheus.flist
        target: azmy/base.flist azmy/prometheus-bins.flist
        token: ${{ secrets.HUB_TOKEN }}
