name: Release (development)
on:
  push:
    paths:
      - 'prometheus/**'
      - '.github/workflows/prometheus.yaml'

jobs:
  build:
    name: Build And Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code into the Go module directory
      uses: actions/checkout@v1

    - name: Build binaries
      run: |
        make prometheus archive=${{ github.workspace }}/build/prometheus

    - name: Publish flist (binaries only)
      if: success()
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: publish
        user: tf-autobuilder
        root: build/prometheus
        name: prometheus-bins-2.18.1.flist

    - name: Publish flist
      uses: threefoldtech/publish-flist@master
      with:
        action: merge
        user: tf-autobuilder
        name: prometheus-2.18.1.flist
        target: azmy/base.flist tf-autobuilder/prometheus-bins-2.18.1.flist
        token: ${{ secrets.HUB_JWT }}

    - name: Crosslink flist
      if: success() && github.ref == 'refs/heads/master'
      uses: threefoldtech/publish-flist@master
      with:
        token: ${{ secrets.HUB_JWT }}
        action: crosslink
        user: tf-official-apps
        name: prometheus:latest.flist
        target: tf-autobuilder/prometheus-2.18.1.flist
